### ISSUE TITLE
Support empty organizations

### ISSUE THREAD

**Issue by patrijst** [iokiwi/jsd-bulk-customer-upload#16]
To bulk import customers only, not related to any organizations. No value should be accepted.

**Comment by iokiwi** [comment]
Hi @patrijst,

Just letting you know I have seen your issue and agree that this should be added. I will look to at this when I get time,  hopefully over the next week.

Otherwise, feel free to raise a pull request

Regards,
Simon

**Comment by patrijst** [comment]
Awesome, working on a project for a customer where your script is very
useful, would like to use it first week of January.
It would also be great if duplicate customer accounts would be accepted, so
they can be a part of multiple organizations.

Organization | Name | Address
A | John Doe | john.doe@local
B | John Doe | john.doe@local

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 17 December 2020 at 23:48:25, Simon Merrick (notifications@github.com)
wrote:

Hi @patrijst <https://github.com/patrijst>,

Just letting you know I have seen your issue and agree that this should be
added. I will look to at this when I get time, hopefully over the next week.

Otherwise, feel free to raise a pull request

Regards,
Simon

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/16#issuecomment-747747853>,
or unsubscribe

**Comment by iokiwi** [comment]
Ack. I have raised this as a seperate issue https://github.com/iokiwi/jsd-bulk-customer-upload/issues/18

**Comment by iokiwi** [comment]
Should be supported now, just omit Organisation name at beginning but retain the comma to tell the CSV parser that its an empty column

```
,John Doe,joh.doe@example.com
```
