### ISSUE TITLE
Jira 7.13 compatibable

### ISSUE THREAD

**Issue by patrijst** [iokiwi/jsd-bulk-customer-upload#20]
Hi there,

I've made some small adjustments to make it compatible with Jira 7.13, could I create a branch / tag for that?

**Comment by iokiwi** [comment]
Absolutely! Pull requests welcome.

The usual github workflow would be 

1. Fork the repo
2. Push your change to your for (or a branch on your fork)
3. Open a pull request from your fork to my upstream origin.

If it makes it easier for you I can add you as a contributor so you can open a branch on this repo.

**Comment by patrijst** [comment]
Not a git hero but I've added my branch to your repo and then forked it, if
you want you can remove the branch from your repo and keep it on the fork
:)

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 19 February 2021 at 01:41:46, Simon Merrick (notifications@github.com)
wrote:

Absolutely! Pull requests welcome.

The usual github workflow would be

   1. Fork the repo
   2. Push your change to your for (or a branch on your fork)
   3. Open a pull request from your fork to my upstream origin.

If it makes it easier for you I can add you as a contributor so you can
open a branch on this repo.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/20#issuecomment-781732394>,
or unsubscribe

**Comment by iokiwi** [comment]
Thanks very much for the Pull request @patrijst. Greatly appreciated :D
