### ISSUE TITLE
Python 3.9 compatible

### ISSUE THREAD

**Issue by patrijst** [iokiwi/jsd-bulk-customer-upload#21]
It doesn't work with 3.9, it does work for 3.7

**Comment by iokiwi** [comment]
Are you please able to post logs?

**Comment by patrijst** [comment]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py",
line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py",
line 87, in _run_code
    exec(code, run_globals)
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/__main__.py",
line 1, in <module>
    from bulk_customer_import import bulk_customer_import
  File
"/Users/patrijst/Projects/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py",
line 4, in <module>
    from client.base import get_client
  File "/Users/patrijst/Projects/jsd-bulk-customer-upload/client/base.py",
line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I guess this is needed?

py -3.9 -m pip install requests

if so, perhaps add it to the readme

*-- please reply above this line --*

Met vriendelijke groet / Kind regards,

Avisi Consultancy B.V.
Patrick van der Rijst

On 19 February 2021 at 01:38:35, Simon Merrick (notifications@github.com)
wrote:

Are you please able to post logs?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iokiwi/jsd-bulk-customer-upload/issues/21#issuecomment-781731346>,
or unsubscribe

**Comment by iokiwi** [comment]
Ah yep! reuqests was included in requirements.txt but have updated README with instructions to create virtualenv (optional) and install dependencies
